### PR TITLE
Make plugins autoload more consistent (fix #268)

### LINKED ISSUE #268: Request: Autoload Plugins w/Programmatic
When used programmatically, fly doesn't autoload & mount plugins, even though tasks are defined.

Minimal example: after creating new project, create following `index.js` and run `node index.js`

``` js
const Fly = require('Fly')
const fly = new Fly({
  tasks: {
    * default (fly){ yield fly.source('x.sass').sass().target('.') }
  }
})
fly.start()
```

Expected: new `x.css` file.
Actual result: `Unhandled rejection TypeError: fly.source(...).sass is not a function`

I've also created minimal repo. Edit: Taken down since.

Node v6.9.1 LTS, npm v4.4.4, yarn v0.21.3

### PR DESCRIPTION
**Pull request by karimsa**
This PR is to make the autoloading of `fly-*` plugins more consistent as per #268.

The way this is done is by moving the plugin autoloading from the cli spawing process directly into the fly class. That way the autoloading occurs under both cases: for CLI-use as well as with manual use.

### CODE REVIEW

**Comment by karimsa** [comment]
@jbucaran - informally requesting review; I've fixed the failing tests.

**Comment by jorgebucaran** [comment]
@karimsa Thanks!

**Comment by karimsa** [comment]
Just wanted to bump this PR.

**Comment by jorgebucaran** [comment]
@karimsa This branch has conflicts with the master branch. You have to rebase and apply your changes on top of the latest master.

screen shot 2017-07-02 at 16 48 37

**Comment by jorgebucaran** [comment]
Please don't update the LICENSE file.

**Comment by karimsa** [comment]
Sorry, that was the merge conflict between the master when I created this PR & now.

I believe it should work now. The only thing is the error handling - how did you want me to implement that? Just emit an error event on `this`?

**Comment by jorgebucaran** [comment]
Thanks @karimsa. I think @lukeed can take it from here. 👋😉

**Comment by lukeed** [comment]
Hi all! 👋 Sorry, I forgot to get to this after the adjustments were happening.

Thanks for your work @karimsa 🙏 I attempted to solved #268 on my own too, and arrived at nearly the exact same code.

The problem is that `Bluebird.coroutine` is ***not*** blocking, unlike the popular alternative `tj/co`. So what happens is that if, for whatever reason, the `plugins.load` is slower than the rest of the calls, your instance & tasks will fire off without any plugins loaded. (This is the case on practically all <= 3yr old machines.)

Worse, because of the `this.pluginsReady` flag, the "internal" `*_start` method has the option to _never_ fire --- and that, indeed, is the what's happening here with Travis. This is also why you needed to call `fly.start()` inside the tests' `spawn()` helper. Is definitely a major, breaking change.

You're not alone though. I had similar issues, and this is why I punted the branch. You can see my explantation [here](https://github.com/lukeed/taskr/issues/268#issuecomment-291574085).

For a simple run-down, this code block summarizes the problem perfectly:

```js
const co = require('bluebird').coroutine;
const sleep = ms => new Promise(res => setTimeout(res,ms));

function test() {
  console.log('1');
  co(function * () {
    console.log('2 - inside');
    yield sleep(3000);
    console.log('3 - slept');
  })();
  console.log('4 - done?');
}

test();
```

Your output will be:

```
1
2 - inside
4 - done?
undefined
> 3 - slept
```

Thanks again for the time you spent on this, @karimsa! I do appreciate it, but unfortunately I can't merge this at this time. 💔 😿 

I have an idea for how to approach this in the near-future. I'll ping you at such time for a second set of eyes.

**Comment by karimsa** [comment]
Sounds good. I'll be closing my fork for now.

**Pull request closed without merging**
