### PR TITLE
Move fly-util into Fly's core

### PR DESCRIPTION
**Pull request by lukeed**
@bucaran take a look? Didn't do any real heavy-lifting since it's going to be reworked soon anyway.

All fixtures, files, and test ported over. 

Had issue with Babel versions (of course). For some reason, 3 packages were resolving to `babel-core@6.5` despite having declarations for `babel-core@^5.8`... The caret is supposed to keep it below the next major version :angry: 

So, at first I just removed the "bind to babel" test, thinking it was no big deal. Then I remembered that the `unknown option: base.stage` would also affect the bin.

Now I'm working on hard-coding a `babel-core@5.8` into the main `package.json`... Will update on my progress :sleepy:

### CODE REVIEW

**Comment by ghost** [comment]
Looking great man! Finally, this means `fly-util` has its days counted.

**Comment by lukeed** [comment]
Can't wait for the ES5 version :stuck_out_tongue_closed_eyes: 

Right now making package.json changes, clearing cache, then waiting ~5m for results. Rinse repeat.

**Comment by lukeed** [comment]
@bucaran ... upgraded to babel 6, lolol

We also don't need a `build` step anymore, nor the `dist` directory :raised_hands: 

I ran the bin executable just fine. No `_regeneratorRuntime` errors like we were getting months ago, but that's because instead of trying to build for runtime, it's set to just compile on the fly like our tests always have. (pun intended)

I will test in a local project before merging, but so far I don't see/feel any performance hits at all.

**Comment by lukeed** [comment]
Something wrong with this test! My guess is that `util.bind` is initializing a second Babel instance, and that causes Node <4 to throw this "OUT OF MEMORY" error.

Again, will test on a real project that uses Babel and I'll find out shortly if this is fatal.

But, do we even need to pass in babel `presets` on function call if we're kicking it all off with babel-node anyways?

**Comment by lukeed** [comment]
All tests pass... but completely explodes inside a project.

**Comment by ghost** [comment]
It will be so exciting to get rid of Babel when I can get on this. Looking at [this](https://babeljs.io/docs/plugins/#presets) makes me cry :sob:

**Comment by lukeed** [comment]
Yup, now you can relate to my comment on our other discussion... I might give another effort towards this later tonight. :sleepy:

**Comment by ghost** [comment]
I used to love the old Plug&Play™ and ItJustWorks™ Babel. It seems to me today's Babel is trying to fix everyone's problems maybe? which is in turn, forcing me to be aware of things I don't want to be aware of. I do thank Babel for letting me discover ES6 early, but nowadays I dread `npm i <p>` where `<p>` is any project that includes Babel as a dep, e.g, Fly.

**Comment by lukeed** [comment]
Exactly -- an over-correction in modularity. 

They strapped dynamite to their chest & blew up into a million little pieces, saying, "For your convenience, you can now pick and choose what features you want...just figure out how to make them fit together lolz"

**Comment by ghost** [comment]
To be fair, they are being explicit about this and offering all links to presets and modules you need to get stuff done, but I don't like that it has essentially become a _configuration first_ system. 

Their website now says:

> Out of the box Babel doesn't do anything.

**Comment by lukeed** [comment]
Me neither, hence the argumentum ad absurdum.

The es2015 covers 99% of use cases alone. But the obscurity & lack of documentation is apparent when dealing with bable's runtime, "node", polyfills, etc. Could definitely use some more docs about those, considering the majority of their Phabricator issues are something to do with runtime.

**Comment by ghost** [comment]
As ES6 becomes more and more widespread, is Babel going to be more or less popular? 

I remember when I first saw the discussion regarding 6.0, I knew this was going places I didn't want to go.

**Comment by lukeed** [comment]
lol, same page completely bud.

I imagine it hit its peak already. Now we're at the point with options: Traceur picking back up, Closure, Typescript... The lion's share is still with Babel, but I've noticed a small wave of forums who migrate elsewhere (or even renounce ES2015 entirely, for now, because they're so fed up with current state of JS).

**Comment by lukeed** [comment]
The more we talk about it the sooner I want to start the ES5 rewrite, lol :fire:

**Comment by ghost** [comment]
untitled

**Comment by lukeed** [comment]
@bucaran this solves it :+1: :tada: 

There's ONE catch -- plugins can't use ES6 `export default function....` syntax. But that's not a massive hindrance considering that we're soon moving away from ES6 altogether.

**Comment by lukeed** [comment]
... Just kidding. Added an additional (for the time being) so that existing ES6 plugins don't break.

Future docs (and generator) will enforce `module.exports = ...`

**Comment by ghost** [comment]
Right, there are plugins written in ES6. I went too far...

**Comment by lukeed** [comment]
Haha even I've made some es6 plugins. Whoopsy

**Comment by ghost** [comment]
I don't know if you'll remember, but the original idea was so that you didn't even have to transpile plugins written in ES6, but that Fly would transpile them in memory in the _fly_ for you.

**Comment by lukeed** [comment]
Right, definitely not a bad idea at all! Just no longer pertains to the project goals.

**Comment by lukeed** [comment]
Anyway, if you can give this a quick test that'd be sweet. Then I'll release as 0.9.0

On my end, works within my "kits" and a personal project.

**Comment by ghost** [comment]
:+1: OK I'll ping you again.

**Comment by lukeed** [comment]
Thank you sir. Extra eyes never hurt.

**Comment by lukeed** [comment]
@bucaran think we're good here?

**Comment by ghost** [comment]
LGTM :+1:

**Comment by lukeed** [comment]
:raised_hands: :tada:

**Comment by ghost** [comment]
Thanks @lukeed! Fly is going to get some love :heart: starting in March soon after I release 1.0 of you know what. 

And for the 1.0 release a little surprise is in the oven.

**Comment by lukeed** [comment]
Released as 0.9.0.

No problem! I started the es5 rewrite locally (small chunks). Getting to a point where I can test out my plans -- hopefully you got my email yesterday.

So far so good.

**Comment by ghost** [comment]
Yes, about the email, tl;dr is I agree with you and the most important upcoming change is only to rewrite Fly in ES5.

**Pull request merged**
