### PR TITLE
doc: fix task cascading intro and outdated section

### PR DESCRIPTION
**Pull request by frantic1048**
I'm translating this documentation to Chinese. And I found this section kind of weird.

May the section actually want to explain what I committed. (っ- ‸ – ς)

### CODE REVIEW

**Comment by frantic1048** [comment]
And, I found `npm run setup` is not available in **Hacking** section. The script `setup` does not exist.

The same with the following `fly -f examples` section.

Should we remove that ?

**Comment by lukeed** [comment]
Sure 👍

**Comment by frantic1048** [comment]
I replaced hacking section's symlinking with `npm link` method. How about now ?

**Comment by ghost** [comment]
Haha what is Chino?

**Comment by frantic1048** [comment]
Well, Chino Kafū (香風 智乃 Kafū Chino?) is the main protagonist of the Is the Order a Rabbit? manga series as well as it's anime series. (http://gochiusa.wikia.com/wiki/Chino_Kaf%C5%AB)

**Comment by lukeed** [comment]
Thank you @frantic1048 🙌

**Pull request merged**
