### PR TITLE
ES5 Version

### LINKED ISSUE #80: separate Fly and CLIEngine
_Fly_ the utility people can download via `npm i fly` would continue to be this repo.

The top priority is to move `fly.js` which exports the Fly class should into its module `fly-core`.

`cli/*.js` could stay or go into its own `fly-cli` too. 

The least priority is moving `fmt.js` to `fly-fmt`.

### LINKED ISSUE #100: No export with require('Fly')
The following snippet throws a `object is not a function`(iojs v2.3.3) or `Fly is not a function`(iojs v3.2.0) error.

``` js
let Fly = require('fly');
const fly = new Fly();
```

---

[_Discussion on Gitter_](https://gitter.im/flyjs/fly?at=55e655fee5564d685efaff5b)

### LINKED ISSUE #109: Tasks descriptions missing from output for cli.list
When adding @desc comments to tasks they are not printed in the output of `cli.list`, although this behavior is expected according to the [documentation](https://github.com/flyjs/fly/tree/cb53bf771cec252a58e48f280a6e573ad051ca34/docs#features).

``` js
export async function copy() {
    /** @desc copies all files from source to distribution */
    return await this.source(paths.source).target(paths.distribution);
}
```

```
fly --list
Available tasks

  "copy"
```

This appears to be a problem with:
- Missing [unit tests](https://github.com/flyjs/fly/blob/master/test/cli.js#L34)
- babel gobbling up the comments when transpiling
- different babel configs for building fly (hardcoded in package.json, flyfile), fly tests (babel-node, hardcoded in package.json) and comprehending fly-files and fly-plugins (require-hook, hardcoded in cli/spawn)

### LINKED ISSUE #120: Babel 6 + .babelrc -> TypeError: Cannot read property 'error' of undefined
After update to `babel@6` I faced following issue: when I place `.babelrc` file in the root — build fails. When I remove it — `fly` runs fine.

Repo to reproduce: https://github.com/alexfedoseev/fly-babel-6-issue

``` js
/* .babelrc */

{
  "presets": ["es2015", "stage-3"]
}
```

``` js
/* flyfile.js */

export default async function() {
  console.log('!');
}
```

Screen:

screen shot 2015-12-14 at 14 18 26

Stack:

```
$(npm bin)/fly
stack:
  - TypeError: Cannot read property 'error' of undefined
  -     at OptionManager.mergeOptions (~/Dev/Sandboxes/tmp/fly-babel-6-issue/node_modules/fly-util/node_modules/babel-core/lib/transformation/file/options/option-manager.js 126:28)
  -     at OptionManager.addConfig (~/Dev/Sandboxes/tmp/fly-babel-6-issue/node_modules/fly-util/node_modules/babel-core/lib/transformation/file/options/option-manager.js 107:10)
  -     at OptionManager.findConfigs (~/Dev/Sandboxes/tmp/fly-babel-6-issue/node_modules/fly-util/node_modules/babel-core/lib/transformation/file/options/option-manager.js 168:35)
  -     at OptionManager.init (~/Dev/Sandboxes/tmp/fly-babel-6-issue/node_modules/fly-util/node_modules/babel-core/lib/transformation/file/options/option-manager.js 229:12)
  -     at compile (~/Dev/Sandboxes/tmp/fly-babel-6-issue/node_modules/fly-util/node_modules/babel-core/lib/api/register/node.js 117:22)
  -     at normalLoader (~/Dev/Sandboxes/tmp/fly-babel-6-issue/node_modules/fly-util/node_modules/babel-core/lib/api/register/node.js 199:14)
  -     at Object.require.extensions.(anonymous function) [as .js] (~/Dev/Sandboxes/tmp/fly-babel-6-issue/node_modules/fly-util/node_modules/babel-core/lib/api/register/node.js 216:7)
  -     at Module.load (module.js 356:32)
  -     at Function.Module._load (module.js 313:12)
  -     at Module.require (module.js 366:17)
  -     at require (module.js 385:17)
  -     at Object.spawn$ (~/Dev/Sandboxes/tmp/fly-babel-6-issue/node_modules/fly/dist/cli/spawn.js 39:29)
  -     at tryCatch (~/Dev/Sandboxes/tmp/fly-babel-6-issue/node_modules/babel-runtime/regenerator/runtime.js 72:40)
  -     at GeneratorFunctionPrototype.invoke [as _invoke] (~/Dev/Sandboxes/tmp/fly-babel-6-issue/node_modules/babel-runtime/regenerator/runtime.js 334:22)
  -     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (~/Dev/Sandboxes/tmp/fly-babel-6-issue/node_modules/babel-runtime/regenerator/runtime.js 105:21)
  -     at onFulfilled (~/Dev/Sandboxes/tmp/fly-babel-6-issue/node_modules/co/index.js 65:19)
message: Cannot read property 'error' of undefined
```

### LINKED ISSUE #140: TypeError: this.source(...).less is not a function
`TypeError: this.source(...).less is not a function` using your example.

### LINKED ISSUE #141: message: Maximum call stack size exceeded
Hi. I try to use Fly v0.9.1, but it doesn't work in part of environments Node v4 and npm v2.
I develop [fly-ava](https://github.com/pine613/fly-ava) plugins, and also use it, so I've found errors as the following.

```
message: Maximum call stack size exceeded
stack: 
  - RangeError: Maximum call stack size exceeded
  -     at Function.isArray (native)
  -     at reduce (~/build/pine613/fly-ava/node_modules/fly/dist/utils/bind.js 37:13)
  -     at reduce (~/build/pine613/fly-ava/node_modules/fly/dist/utils/bind.js 43:14)
  -     at reduce (~/build/pine613/fly-ava/node_modules/fly/dist/utils/bind.js 43:14)
  -     at reduce (~/build/pine613/fly-ava/node_modules/fly/dist/utils/bind.js 43:14)
  -     at reduce (~/build/pine613/fly-ava/node_modules/fly/dist/utils/bind.js 43:14)
  -     at reduce (~/build/pine613/fly-ava/node_modules/fly/dist/utils/bind.js 43:14)
  -     at reduce (~/build/pine613/fly-ava/node_modules/fly/dist/utils/bind.js 43:14)
  -     at reduce (~/build/pine613/fly-ava/node_modules/fly/dist/utils/bind.js 43:14)
  -     at reduce (~/build/pine613/fly-ava/node_modules/fly/dist/utils/bind.js 43:14)
```

https://travis-ci.org/pine613/fly-ava/jobs/110563430

I think that `reduce` util function has bugs.
https://github.com/bucaran/fly/blob/master/src/utils/bind.js#L21-L33

This code runs forever.

```
reduce([]);
```

Thank you.

### PR DESCRIPTION
**Pull request by lukeed**
### Changes
- Rewrites everything into ES5, dropping Babel as a core dependency.
- Flyfiles must be written in ES5 (`module.exports` & `generators/yield` only). `fly-esnext` will allow you to write in ES6/7
- Flyfiles must be named `flyfile.js`. `Flyfile.js` is no longer recognized.
- Removes some old `fly-util` helpers in favor of NPM packages: `expand`, `flatten`, `filter`
- Added new `util` helpers: `find`, `read`
- Moved `src` directory to `lib` and removed `dist` since there is no build step.
- Moved `bin/index` to `cli.js`
- Changed ESLint styling. Now uses out-of-the-box setup from [XO](https://github.com/sindresorhus/xo)
- Custom `timestamp()` function for CLI timestamps, in place of heavy `dateformat` dep.
- Dropped `mz` dep. Wrapping `fs.writeFile` with `thenify` instead
- Task descriptions re-enabled. Closes #109 
### Metrics
- CLI executable runs in `~130ms` compared to `1.4s` with Babel
- The _slowest_ test w/ Travis completes in `1m 39s` compared to `4m` with Babel (included compile step)
- More reliable test comparison: Full test suite completes in `~570ms` compared to `1.8s` with Babel (no compile step)
### Babel-related Issues to Close

Closes #141. Closes #120. Closes #141.
### Other Issues

Closes #140. Closes #80.
### Todo
- [x] Add new `write` util, drop `thenify` as dep.
- [ ] Extract plugin logic to `fly-plugins`
- [ ] Add new plugin 'mounting' structure to `fly-plugin` for more flexible & easier plugin creation.
- [x] Export Fly from main CLI file. (Closes #100)
- ~~[ ] `cli.options`: Catch all tasks, only reads first~~ Opened Issue [here](https://github.com/bucaran/parsec/issues/9)
- [ ] Do we really need `interpret`? (`utils.bind`)

### CODE REVIEW

**Comment by lukeed** [comment]
The _slowest_ Travis test finishes in `1m 39s`... compared to previous versions' `4m+` :tada:

**Comment by lukeed** [comment]
Merging so that I can publish as `beta` and start testing.

**Comment by ghost** [comment]
:+1:

**Comment by lukeed** [comment]
@bucaran oh hi, just pinged ya on gitter

**Pull request merged**
