### PR TITLE
Update tests because of clor update - Fix bucaran/fly#122

### PR DESCRIPTION
**Pull request by marvinroger**

### CODE REVIEW

**Comment by marvinroger** [comment]
I also added Travis caching and fixed david-dm link in the README. ;)
This will make Travis testing waaaay faster.

**Comment by lukeed** [comment]
Not super versed in Travis mechanics, but does this make Travis will ignore package.json / dependency changes?

**Comment by marvinroger** [comment]
No it won't, `npm install` will still be ran, but it won't need to download already fetched dependencies. But if you update `package.json` deps, and there is a newer dep version available, it will download it normally.

**Comment by lukeed** [comment]
Awesome, good to know. Thanks

**Comment by lukeed** [comment]
This still produces a faulty Fly.js due to Babel runtime issues. Run `./bin/index` after passing `npm run build` to see error.

I already have a PR waiting that fixes this, so no need to worry @bucaran @marvinroger :smile: 

I'll rebase & open the PR once this has been merged. :+1:

**Comment by marvinroger** [comment]
How did you fix it?

**Comment by ghost** [comment]
Very helpful @marvinroger and thanks! I'd like to merge this, but I'll wait on @lukeed status report regarding:

> I already have a PR waiting that fixes this...

**Comment by lukeed** [comment]
@bucaran merge this first. I'll rebase from it :grinning:

**Comment by ghost** [comment]
:+1: Great!

**Pull request merged**
