### PR TITLE
Fix new `utils.find` for Windows

### PR DESCRIPTION
**Pull request by lukeed**
Looks like to got detached?

### CODE REVIEW

**Comment by lukeed** [comment]
Nope, integration still there. Will fix this bug when I return. Traveling for next couple hours. ✈️

**Comment by hzlmn** [comment]
Man you done so much work, have a safe trip!

**Comment by lukeed** [comment]
Thanks! It's time that Fly FINALLY releases 2.0 =D

**Comment by lukeed** [comment]
I will release the next beta tonight or tomorrow, after I've fixed this Windows bug.

**Pull request merged**
