### PR TITLE
Fix formatting issues when process.env.HOME is undefined

### PR DESCRIPTION
**Pull request by sylvainpolletvillard**
fix for https://github.com/flyjs/fly/issues/101

### CODE REVIEW

**Comment by lukeed** [comment]
Quick question, do you have `process.env.USERPROFILE` defined?

**Comment by sylvainpolletvillard** [comment]
Yes

image

Also I have process.env.HOMEPATH defined

**Comment by lukeed** [comment]
Ok. Do me a favor and try this instead:

``` js
var home = process.env[(process.platform === 'win32') ? 'USERPROFILE' : 'HOME']
var msg = pretty.render(e)
    .replace(/(\sFunction|\sObject)\./g, clor.blue('$1') + '.')
    .replace(/\((~?\/.*)\)/g, '(' + clor.gray('$1') + ')')
    .replace(/:([0-9]*):([0-9]*)/g, ' ' + clor.yellow('$1') + ':' + clor.yellow('$2'))
    .replace(new RegExp(home, 'g'), '~')
console.error(msg)
```

**Comment by lukeed** [comment]
@sylvainpolletvillard I'll take care of the lint errors. Thank you! 🙌

**Pull request merged**
