### PR TITLE
Clormetics: Clor + Cosmetics

### PR DESCRIPTION
**Pull request by jorgebucaran**
Switch back to clor.

Cosmetic changes: bring back double quotes and remove `;`.

### CODE REVIEW

**Comment by lukeed** [comment]
Can you please add the `.editorconfig` back in? You may not use it, but it's actually quite popular & autofixes a bunch of spacing.

**Comment by lukeed** [comment]
Thanks! I'm just waiting for AppVeyor to finish testing.

**Comment by jorgebucaran** [comment]
I can understand that, as I was into it before. I don't like it so much now, but you have a point. I put it back!

**Comment by lukeed** [comment]
You dropped my XO 😿 

Any chance I can compromise with you? I'll trade you no-semis for using single quotes instead

**Comment by jorgebucaran** [comment]
What do you say we go without xo for a while. If you feel uncomfortable without it after that, then by all means put it back! 👍

**Comment by lukeed** [comment]
It's actually quite painful (double quotes) haha. It's two keystrokes for one one character, every time.

I'm okay dropping XO. But we should get a customized ESLint replacement in the future. It'd be silly not to.

**Comment by jorgebucaran** [comment]
I don't like linters, but I won't oppose you if you really feel the show can't go on without one.

**Comment by lukeed** [comment]
It's a good idea to, especially once others start contributing again. It gets really messy quite quickly, which is something you admitted about Fly 0.8

**Comment by hzlmn** [comment]
This style is quite similar to [standard](https://github.com/feross/standard) except double quotes.

**Comment by lukeed** [comment]
@hzlmn 👋 Correct! Can we all agree on single quotes?

**Comment by jorgebucaran** [comment]
I always use double quotes and it was double quotes once before.

**Comment by lukeed** [comment]
So, no compromises? I see.

**Comment by hzlmn** [comment]
As for me, styling problems are not problems at all. I think as Jorge is original author we can agree with his decision. Does it work for you? @lukeed

**Comment by jorgebucaran** [comment]
Actually, here is the back story, it is _way_ harder to type single quotes for me, since my keyboard is in Japanese and the ' is the weirdest position. 

EDIT: It's above the number 7, so I'd need to type shift+7, lol. " is just shift+2

**Comment by lukeed** [comment]
That sucks! lol

Luckily 2.0 is almost done. Not many `"` left to be typed.

**Comment by jorgebucaran** [comment]
> So, no compromises? I see.

IIRC `"` is on the same spot in English keyboards? So, technically this makes us even!

Thanks 🙇 for merging.

**Comment by lukeed** [comment]
Yea, it is. My point was that `'` is 1 keystroke (<kbd>'</kbd>) and `"` is 2 (<kbd>Shift</kbd> + <kbd>'</kbd>). Just a redundant stroke every time 😜, adds up tho.

**Comment by jorgebucaran** [comment]
I said I dislike linters, but I'd be thrilled to give https://github.com/jlongster/prettier a try. I am used to syntax formatters like gofmt, and I think they are fabulous.

**Comment by lukeed** [comment]
Okay, would be curious to try it out. But we would wait on this one in particular. I've already seen at least 2 format changes since I heard about it.

**Pull request merged**
