### PR TITLE
Added appveyor build

### PR DESCRIPTION
**Pull request by hzlmn**
Discovered some problems with globs.

### CODE REVIEW

**Comment by lukeed** [comment]
@hzlmn This is because we're manually declaring the `/` path syntax now. The `path.join` instances within tests will resort to Node's decision: `\\` I forgot to update this in the tests.

**Review by lukeed — CHANGES_REQUESTED** [review]
Sorry for the delay @hzlmn! 

Can you make this a _slightly_ smaller PR that only adds the AppVeyor file?

Also, I updated the `test` script so that you don't have to run a separate command for Windows.

**Comment by hzlmn** [comment]
@lukeed ok

**Comment by hzlmn** [comment]
@lukeed Updated this one.

**Comment by lukeed** [comment]
Thank you @hzlmn !

**Comment by lukeed** [comment]
Is there a way to add a Readme badge to make this easily accessible? I don't know how to see or trigger new AppVeyor builds.

**Comment by hzlmn** [comment]
@lukeed I do not have rights for this repo. Basically, process is similar to `Travis`, go to `appveyor` site -> log with github -> add repo -> then build will be triggered on each PR, commit.

**Comment by lukeed** [comment]
@hzlmn Ah ok, thanks. Nor do I. @jbucaran

**Pull request merged**
