### PR TITLE
fix readme.md path

### PR DESCRIPTION
**Pull request by pine**

### CODE REVIEW

**Comment by lukeed** [comment]
Hey pine! I'm not going to merge simply because the entire readme is about to be changed -- hope that's okay. 😟 

Thanks!

**Comment by jorgebucaran** [comment]
@lukeed The entire readme?

**Comment by lukeed** [comment]
Yes @jbucaran

**Comment by jorgebucaran** [comment]
@lukeed Yes, it needs emoji.

**Comment by pine** [comment]
> I'm not going to merge simply because the entire readme is about to be changed -- hope that's okay.

OK. Thanks.

**Pull request closed without merging**
