### PR TITLE
Update Travis CI configuration

### PR DESCRIPTION
**Pull request by mrmlnc**
:guitar: :tractor:

### CODE REVIEW

**Comment by mrmlnc** [comment]
Okay, okay, I'll do this today. :muscle:

**Comment by iamstarkov** [comment]
up-to-date versions are `v5`, `v4`, `0.12`, `0.10`. take a look at https://www.npmjs.com/package/generator-travis

**Comment by mrmlnc** [comment]
Hell yeah!

The problem is caused by an update Babel.

**Comment by ghost** [comment]
:anguished:

**Comment by mrmlnc** [comment]
@bucaran The easiest way to limit the version of Babel up to 5. On Babel 6 I get errors:

Error:

``` js
Error: src/cli/index.js: Invariant Violation: To get a node path the parent needs to exist
```

Is solved as follows:

``` js
export { help } from "./help"
export { list } from "./list"
export { version } from "./version"
export { spawn } from "./spawn"
export { options } from "./options"
```

Error:

``` js
SyntaxError: src/fly.js: 'this' is not allowed before super() (This is an error on an internal node. Probably an internal error)
```

Is solved as follows:

``` js
// I don't know.
```

**Comment by iamstarkov** [comment]
yep, for now its better to stick to babel v5 until they fix most of the bugs

**Pull request merged**
